version: "3"
services:
  webssh:
    image: 'antonyxu/webssh'
    container_name: webssh
    restart: unless-stopped
    user: 1000:1000
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
