version: '3'
services:
  filebrowser:
    restart: unless-stopped
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data:/srv
      - ./database.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
