version: "3"
services:
  v2ray:  # 1080
    image: antonyxu/v2ray
    container_name: v2ray
    restart: unless-stopped
    volumes:
      - ./config/config.json:/etc/v2ray/config.json
      - ./config:/var/log/v2ray

networks:
  traefik_default:
    external: true
