name: Docker Build CI

on:
  # schedule:
  #   - cron: '0 2 */1 * *' # On the 1st of every month
  push:
    branches: [ "master" ]

jobs:
  FrpBuildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push the Docker image
      run: |
        cd v2ray && docker build . -t antonyxu/v2ray && cd ..
        cd webdav && docker build . -t antonyxu/webdav && cd ..
        cd webssh && docker build . -t antonyxu/webssh && cd ..
        cd transmission && docker build . -t antonyxu/transmission && cd ..
        # cd anime_updater && docker build . -t antonyxu/anime_updater && cd ..
        docker push antonyxu/v2ray
        docker push antonyxu/webdav
        docker push antonyxu/webssh
        docker push antonyxu/transmission
        # docker push antonyxu/anime_updater
    - uses: docker/build-push-action@v3.1.1
      with:
        context: anime_updater
        push: true
        tags: antonyxu/anime_updater:latest
